# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-19 19:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20151206_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='slug_da',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='slug_en',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
