# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-19 20:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20160319_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='slug',
            field=models.SlugField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='slug_da',
            field=models.SlugField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='slug_en',
            field=models.SlugField(blank=True, max_length=100, null=True),
        ),
    ]
