# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-26 18:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20160319_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='created_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='modified_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
